services:
  app:
    build:
      context: ./laravel
    container_name: laravel-app
    volumes:
      - ./laravel:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - BROADCAST_DRIVER=reverb
      - CACHE_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - DB_CONNECTION=mongodb
      - MONGO_DB_HOST=mongo
      - LARAVEL_REVERB_APP_ID=app-id
      - LARAVEL_REVERB_APP_KEY=app-key
      - LARAVEL_REVERB_APP_SECRET=app-secret

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

   
  reverb:
    build:
      context: ./reverb
    container_name: reverb
    depends_on:
      - app
    ports:
      - "6001:6001"
    environment:
      - LARAVEL_REVERB_APP_ID=app-id
      - LARAVEL_REVERB_APP_KEY=app-key
      - LARAVEL_REVERB_APP_SECRET=app-secret

  node:
    image: node:20
    container_name: laravel-node
    working_dir: /var/www
    volumes:
      - ./:/var/www
    entrypoint: [ "tail", "-f", "/dev/null" ]
    networks:
      - app-network

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=secret
    depends_on:
      - mongo

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge