version: "3.8"

services:
  app:
    build:
      context: ./laravel
    container_name: laravel-app
    volumes:
      - ./laravel:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - DB_CONNECTION=mongodb
      - MONGO_DB_HOST=mongo

  crawler:
    build:
      context: ./crawler
    container_name: crawler-service
    volumes:
      - ./crawler:/app
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=secret
    depends_on:
      - mongo

volumes:
  mongo_data:
