FROM python:3.13.4-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt \
    && pip install playwright && playwright install --with-deps

# Copy code
COPY . .

CMD ["python", "main.py"]
